export const PETS_DEFAULTS = {
  a_c_chop: {
    speed: 1.0,
    title: 'pet_name_rottweiler',
    friendliness: '0%',
    affection: '50%',
    protection: '100%',
    price: 0.01,
  },
  a_c_husky: {
    speed: 1.0,
    title: 'pet_name_husky',
    friendliness: '40%',
    affection: '90%',
    protection: '50%',
    price: 0.005,
  },
  a_c_retriever: {
    speed: 1.0,
    title: 'pet_name_labrador_retriever',
    friendliness: '100%',
    affection: '100%',
    protection: '10%',
    price: 0.005,
  },
  a_c_poodle: {
    speed: 1.0,
    title: 'pet_name_poodle',
    friendliness: '70%',
    affection: '70%',
    protection: '0%',
    price: 0.0025,
  },
  a_c_westy: {
    speed: 1.0,
    title: 'pet_name_westy',
    friendliness: '75%',
    affection: '75%',
    protection: '10%',
    price: 0.003,
  },
  a_c_shepherd: {
    speed: 1.0,
    title: 'pet_name_shepherd',
    friendliness: '50%',
    affection: '80%',
    protection: '80%',
    price: 0.0075,
  },
  a_c_pug: {
    speed: 1.0,
    title: 'pet_name_pug',
    friendliness: '10%',
    affection: '50%',
    protection: '0%',
    price: 0.005,
  },
  a_c_cat_01: {
    speed: 1.0,
    title: 'pet_name_cat',
    friendliness: '100%',
    affection: '100%',
    protection: '0%',
    price: 0.001,
  },
};
