remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: "/assets/images/logo-transparent-small.png"


collections:
  framework:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    framework:
      name: Framework
